---
title: "Resume"
---
#Ma Runqi

###EDUCATION
Taipei Medical University (TMU), Taipei, Taiwan                                 

Sept. 2014 – 2018

B.S in Public Health 

###WORK EXPERIENCE

Intern at Hangzhou Disease Prevention and Control Center  (Aug. 2017)

* Prepared and sent chronic disease test reports, cause of death test reports, flu reports, etc.
* Audited quality of chronic disease report cards of Hangzhou medical institutions
* Organized pharmacy monitoring data and English documents
* Assisted in public health risk assessments 


Intern at Xinyi District Health Center	(Jul. 2017)

* Helped conduct child screening and national health inspections; entered screening data
* Surveyed the development of children in disadvantaged homes through the use of children’s developmental progress forms 
 Directed attention to cases of possible late development
* Contacted the public to take part in colorectal cancer screenings 
o	Kept records so public health practitioners can deliver screening kits
* Conducted panel discussions on children with vision problems and used the health center’s data for analysis (Panel: “Correlation Between Visions of 4 to 6-Year-Old Children Based on Kindergarten Attendance”)
